{{- $cert := "" -}}
{{- if .Values.minecraft.tls.enabled -}}
{{- $hostname := .Values.minecraft.tls.hostname -}}
{{- if .Values.minecraft.tls.subjectAlternativeNames -}}
  {{- $cert = genSelfSignedCert .Values.minecraft.tls.hostname (list .Values.minecraft.tls.subjectAlternativeNames) (list .Values.minecraft.tls.subjectAlternativeNames) nil 365 -}}
{{- else -}}
  {{- $cert = genSelfSignedCert .Values.minecraft.tls.hostname nil nil 365 -}}
{{- end -}}
apiVersion: v1
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
kind: Secret
metadata:
    name: minecraft-tls-secret
type: kubernetes.io/tls
{{- end -}}
